# Generated by Django 3.2.16 on 2022-11-21 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0005_auto_20221121_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('recycleCoins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('citizen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.citizen')),
            ],
            bases=('core.citizen',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 18, 29, 217794, tzinfo=utc))),
                ('checked', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to='core.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='RecycleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=3)),
                ('unit', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('dateSubmitted', models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 18, 29, 216844, tzinfo=utc))),
                ('status', models.CharField(default='', max_length=255)),
                ('citizen', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.citizen')),
                ('material', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('collector', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='core.collector')),
            ],
        ),
    ]
