# Generated by Django 3.2.16 on 2022-10-29 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recyclerequest_datesubmitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 35, 18, 715886, tzinfo=utc))),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 35, 18, 714780, tzinfo=utc)),
        ),
    ]
