# Generated by Django 3.2.16 on 2022-10-29 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221029_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.citizen'),
        ),
        migrations.AddField(
            model_name='recyclerequest',
            name='collector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='core.collector'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 18, 54, 32, 334483, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 18, 54, 32, 333803, tzinfo=utc)),
        ),
    ]
