# Generated by Django 3.2.16 on 2022-10-30 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221029_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 16, 21, 28, 854290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='collector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='core.collector'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 16, 21, 28, 853222, tzinfo=utc)),
        ),
    ]
