# Generated by Django 3.2.16 on 2022-10-30 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221030_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 16, 23, 25, 406740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='collector',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='core.collector'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 16, 23, 25, 405768, tzinfo=utc)),
        ),
    ]
