# Generated by Django 3.2.16 on 2022-11-15 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221030_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='recycleCoins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 19, 46, 51, 695649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 19, 46, 51, 694985, tzinfo=utc)),
        ),
    ]
