# Generated by Django 3.2.16 on 2022-10-29 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_confirmationcode_expirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 16, 26, 198126)),
        ),
        migrations.AlterField(
            model_name='locationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 16, 26, 202717)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 16, 26, 200715)),
        ),
        migrations.AlterField(
            model_name='twofactorauthcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 17, 16, 26, 201680)),
        ),
    ]
