# Generated by Django 3.2.16 on 2022-11-21 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20221029_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 23, 28, 835673)),
        ),
        migrations.AlterField(
            model_name='locationcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 23, 28, 842110)),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 23, 28, 839104)),
        ),
        migrations.AlterField(
            model_name='twofactorauthcode',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 17, 23, 28, 840471)),
        ),
    ]
